!include ..\rules.mak.bcc32
OBJS=mbfilter.obj mbfl_string.obj mbfl_language.obj mbfl_encoding.obj mbfl_convert.obj mbfl_ident.obj mbfl_memory_device.obj mbfl_allocators.obj mbfl_filter_output.obj mbfilter_pass.obj mbfilter_wchar.obj mbfilter_8bit.obj mbfl_buffer_converter.obj

all: $(OBJS)

clean:
	@for %i in ($(OBJS)) do @if exist %i del %i
