#!/usr/bin/expect -f
proc begin_strcut_test {_from _length} {
    global spawn_id from length
    set from $_from
    set length $_length

    spawn tests/strcut Japanese EUC-JP $_from $_length
    set timeout 1

    expect_after {
        "\[^\r\n\]*\r\n" { fail $test }
    }
}

begin_strcut_test -1 2

set test "asciish characters ($from, $length)"
send "testtest\r"
expect {
    "***ERROR**\r\n" { pass $test }
}

set test "non-asciish characters ($from, $length)"
send "テストテスト\r"
expect {
    "***ERROR***\r\n" { pass $test }
}

close
begin_strcut_test 2 -1

set test "asciish characters ($from, $length)"
send "testtest\r"
expect {
    "***ERROR**\r\n" { pass $test }
}

set test "non-asciish characters ($from, $length)"
send "テストテスト\r"
expect {
    "***ERROR***\r\n" { pass $test }
}

close
begin_strcut_test 3 2

set test "asciish characters ($from, $length)"
send "testtest\r"
expect {
    "tt\r\n" { pass $test }
}

set test "non-asciish characters ($from, $length)"
send "テストテスト\r"
expect {
    "ス\r\n" { pass $test }
}

close
begin_strcut_test 5 8

set test "asciish characters ($from, $length)"
send "testtest\r"
expect {
    "est\r\n" { pass $test }
}

set test "non-asciish characters ($from, $length)"
send "テストテスト\r"
expect {
    "トテスト\r\n" { pass $test }
}

close
begin_strcut_test 1 15

set test "asciish characters ($from, $length)"
send "testestestestestes\r"
expect {
     "estestestestest\r\n" { pass $test }
}

set test "non-asciish characters ($from, $length)"
send "テストテスト\r"
expect {
    "テストテスト\r\n" { pass $test }
}
close


# vim: sts=4 sw=4 ts=4 et encoding=EUC-JP
